= Extending the Volume Group

== The Plan

Now that we've identified the problem (physical volume only using 1GB of a 5GB disk), let's fix it! We need to:

1. Extend the physical volume to use all available space on the disk
2. Verify the volume group automatically picks up the additional space

== Step 1: Identify the Physical Volume and Disk

First, let's confirm which disk and PV we're working with. Run `lsblk` again to identify the device name:

[source,bash,role=execute]
----
lsblk
----

Look for the 5GB disk - it's probably `/dev/vdb`. Note the name of the physical volume (the PV partition on that disk).

[TIP]
====
Your disk might be named `/dev/vdb`, `/dev/sdb`, or something similar depending on your system. Make sure you're looking at the 5GB disk, not the root disk!
====

== Step 2: Extend the Physical Volume

The key command here is `pvresize`. This will extend the physical volume to use all available space on the disk.

First, let's check the current PV size:

[source,bash,role=execute]
----
pvs
----

Now extend the physical volume to use the full disk. Replace `/dev/vdb` with your actual device name if different:

[source,bash,role=execute]
----
pvresize /dev/vdb
----

[NOTE]
====
The `pvresize` command will automatically detect the size of the underlying disk and expand the PV to match. You don't need to specify a size - it's smart enough to figure it out!
====

== Step 3: Verify the PV Extension

Check that the physical volume is now using the full 5GB:

[source,bash,role=execute]
----
pvs
----

You should now see the PV size is approximately 5GB instead of 1GB!

For more detailed information:

[source,bash,role=execute]
----
pvdisplay
----

== Step 4: Check the Volume Group

Now let's verify that the volume group has automatically picked up the additional space:

[source,bash,role=execute]
----
vgs
----

You should see that the volume group now has significantly more free space available!

For details:

[source,bash,role=execute]
----
vgdisplay
----

Look at the "Free PE / Size" line - you should now see about 4GB of free space available in the volume group.

== Understanding What Happened

When you extended the physical volume:

1. The PV grew from ~1GB to ~5GB
2. The volume group automatically recognized the additional PV space
3. The VG now has ~4GB of free extents available for use
4. The logical volume hasn't changed yet - we'll do that in the next step

[IMPORTANT]
====
Notice that this entire operation was done *online* - no downtime required! The filesystem is still mounted and (theoretically) the application could still be running. This is one of the huge advantages of LVM.
====

[quote, Manager Scott]
____
"Wait, you mean we had 4GB of space just sitting there unused this whole time? Well, obviously I knew that. I was just... testing you. Yeah, testing your troubleshooting skills. You passed! Now can you actually give that space to the application?"
____

*Narrator*: Sure, Scott. You were totally testing us.

== Next Steps

The volume group now has plenty of free space, but the logical volume and filesystem don't know about it yet. In the next section, we'll extend the logical volume and resize the filesystem to actually make this space available to the application.
